version: '3.8'

services:

  api_be:
    build: .
    container_name: api_be_PoC
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker_celery
    command: celery -A src.worker worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api_be
      - redis

  redis:
    image: redis:7
    container_name: redisdb_PoC

  dashboard:
    build: .
    container_name: flower_dashboard
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api_be
      - redis
      - worker
